// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFUkWnEAkJw0IInQglIZ0RItHnEZgzng',
    appId: '1:766515137508:web:2bc1b8723148b11b5e95f1',
    messagingSenderId: '766515137508',
    projectId: 'kostify-mobile',
    authDomain: 'kostify-mobile.firebaseapp.com',
    storageBucket: 'kostify-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl4nkkqTNTMu8xfaGG-8McPeE91__I2uc',
    appId: '1:766515137508:android:e58f826660589a415e95f1',
    messagingSenderId: '766515137508',
    projectId: 'kostify-mobile',
    storageBucket: 'kostify-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu4O--qL2WVRQMwPYROskjajIS2eYbueI',
    appId: '1:766515137508:ios:294f24a4b22441bc5e95f1',
    messagingSenderId: '766515137508',
    projectId: 'kostify-mobile',
    storageBucket: 'kostify-mobile.firebasestorage.app',
    iosBundleId: 'com.kostify.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu4O--qL2WVRQMwPYROskjajIS2eYbueI',
    appId: '1:766515137508:ios:08ddfffe9a9002c85e95f1',
    messagingSenderId: '766515137508',
    projectId: 'kostify-mobile',
    storageBucket: 'kostify-mobile.firebasestorage.app',
    iosBundleId: 'com.example.kostHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeFUkWnEAkJw0IInQglIZ0RItHnEZgzng',
    appId: '1:766515137508:web:b16a91dcec9449e85e95f1',
    messagingSenderId: '766515137508',
    projectId: 'kostify-mobile',
    authDomain: 'kostify-mobile.firebaseapp.com',
    storageBucket: 'kostify-mobile.firebasestorage.app',
  );
}